### ISSUE TITLE
No GUI with DXVK 1.3 in DiRT Rally

### ISSUE THREAD

**Issue by Jonas1999** [doitsujin/dxvk#1127]
When running DiRT rally with DXVK 1.3 there is no visible GUI but I can still select the menu options. When loading a rally stage there's no GUI as well. This issue doesn't exist in 1.2.3 and prior.

I installed DXVK 1.3 by copying proton 4.2-9 to the compatibilitytools.d folder and then replacing the DXVK files with the newest released ones(x32 in lib and x64 in lib64 folders). This process has worked flawlessly for me in the past with 1.2.3 and some prior to that.

It seems that I can't provide any logs with 'wine apitrace.exe trace -a dxgi YOURGAME.exe' even though I have wine 4.12.1-dev installed on my system it says that the command 'wine' doesn't exist. I am currently running Fedora 30 if that matters.

### Software information
DiRT Rally, on a 1440p 144hz monitor.

### System information
- CPU:i7-4770k @ 4.5 GHz
- GPU:1060 3gb
- Driver:430.26
- Wine version: 4.2(whatever proton version 4.2-9 uses)
- DXVK version: 1.3
- RAM: DDR3 2000mhz 32GB(8x4) Dual channel

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:
- dxgi.log:

**Comment by doitsujin** [comment]
Fixed by 03c6df56c1a114a2eda77acd49eda865e6363679. I don't fully understand what's going on there, but it looks like a GCC bug (someone did an MSVC build and it works fine there).

Here's a fixed build:
[dxvk-master.tar.gz](https://github.com/doitsujin/dxvk/files/3389261/dxvk-master.tar.gz)

**Comment by aqxa1** [comment]
Interestingly, bug still exists if you compile a winelib build with GCC-8.3.0 but not GCC-9.1.0.
