### ISSUE TITLE
Unsupported Graphics Card detected. A GPU with support for D3D FeatureLevel 11.0 is required.

### ISSUE THREAD

**Issue by sajmonella9** [doitsujin/dxvk#124]
Please describe your issue as accurately as possible. If you run into a problem with a binary release, make sure to test with latest `master` as well.

**Important:** When reporting an issue with a specific game or application, such as crashes or rendering issues, please include log files and a D3D11 Apitrace (see https://github.com/apitrace/apitrace) so that the issue can be reproduced. In order to create a trace, run `wine apitrace.exe trace -a dxgi YOURGAME.exe`. DO NOT use DXVK together with apitrace!

### Software information
Name of the game, settings used etc.

Steam -> Sniper Ghost Warrior 3.

DXVK_HUD=1
DXVK_LOG_LEVEL=trace
DXVK_SPIRV_OPT=ON
DXVK_SHADER_DUMP_OPTIMIZED_PATH="$HOME/dxvk/new_optimized"

"Unsupported Graphics Card detected.
A GPU with support for D3D FeatureLevel 11.0 is required."

### System information
- GPU: NVIDIA GTX 960 4GB OC EVGA
- Driver: 390.25-15
- Wine version: wine-staging 3.3
- DXVK version: 0.30.2

### Apitrace file(s)
- Put a link here

### Log files
- d3d11.log:  Can't share log cuz, game don't wanna start.
- dxgi.log:

**Comment by doitsujin** [comment]
Does it work with wined3d? If there's no log, this means that the game doesn't even try to use D3D11, so it's likely an issue with wine or your configuration in general.

**Comment by asharin75** [comment]
Might be because Wine-staging does not currently have the vulkan dll's that the old 2.21 had, it only has winevulkan as per standard wine 3.3?

**Comment by doitsujin** [comment]
Right, that's also a possibility. I updated the README accordingly.

wine-vulkan has been rebased against wine 3.3 recently, DXVK works well with that branch.

**Comment by sajmonella9** [comment]
i installed wine-vulkan 3.3 V , and still the same problem. I rly don't know how to test my configuration. before i open WoW and Valley Benchmark but no one .log was generated. And i terminal don't see special things from VULKAN libs. I try with dxvk-bin / compiled version to... And nothing . In my opinion i have good things like installed wine-vulkan / libs from dxvk in winelibs. I try open game without dx3d11 and gdxi and game was started normal.

**Comment by doitsujin** [comment]
Try to run the Vulkan demos from the LunarG SDK first (such as cube.exe). If they don't work, something is wrong with your setup.

**Comment by sajmonella9** [comment]
![screenshot_20180305_123632](https://user-images.githubusercontent.com/8018061/36973098-dd720fc0-2071-11e8-8666-b4d2bf69094b.png)

**Comment by doitsujin** [comment]
You really only need to follow [these](https://github.com/roderickc/wine-vulkan/blob/master/README.md) instructions (**including** the autoconf step).

Please also make sure that you **do not** set the `VK_ICD_FILENAMES` environment variable.

**Comment by sajmonella9** [comment]
i skip autoconf step, cuz i install this package from AUR archlinux. And yes, i don't set that varible to env.

**Comment by Yardanico** [comment]
@sajmonella9 did you install vulkan-icd-loader?

**Comment by sajmonella9** [comment]
If u mean linux version then yes. If windows version i install only that Vulkan SDK.

**Comment by Yardanico** [comment]
@sajmonella9 well I still think you have some needed package needed, do you really have it installed?

**Comment by sajmonella9** [comment]
i don't even have dir like /etc/vulkan/ LOL what package i need in archlinux? i'm using nvidia.

**Comment by pchome** [comment]
FYI: wine-vanilla and wine-staging 3.3 have **initial** vulkan support, but you can test your app by simply copying `vulkan.dll.so` and `vulkan-1.dll.so` from wine-staging-2.21 somewhere and setting WINEDLLPATH=/path/to/lib:/path/to/lib32 where you placed them. Also disable `winevulkan` for your prefix. No other settings should be needed.

**Comment by Yardanico** [comment]
@sajmonella9 you don't need to have that folder, just make sure you have proprietary nvidia driver and `vulkan-icd-loader`: `sudo pacman -S vulkan-icd-loader`

**Comment by sajmonella9** [comment]
warning: nvidia-390.25-14 is up to date -- reinstalling
warning: vulkan-icd-loader-1.0.68.0-1 is up to date -- reinstalling

and i export VK_ICD_FILENAMES to correct dir.

**Comment by Yardanico** [comment]
@sajmonella9 well you don't need any exports if you have everything installed

**Comment by sajmonella9** [comment]
When i try open vulkaninfo.exe from Wine.
"Cannot create Vulkan instance.
C:\VulkanSDKBuild\workspace\LoaderAndValidationLayers\demos\vulkaninfo.c:808: failed with VK_ERROR_INCOMPATIBLE_DRIVER
" i have x64 wineprefix .

**Comment by Yardanico** [comment]
@sajmonella9 https://wiki.archlinux.org/index.php/Vulkan#Nvidia_-_vulkan_is_not_working_and_can_not_initialize did you try this?

**Comment by Yardanico** [comment]
@sajmonella9 try to remove `vulkan-intel` package if you have it installed

**Comment by sajmonella9** [comment]
Don't working with / without. ; / How its possible lol. I didn't miss nothing...

**Comment by ChristophHaag** [comment]
> and i export VK_ICD_FILENAMES to correct dir.

Don't, wine-vulkan does not work at all with that variable set.

When running 32 bit applications, make sure lib32-vulkan-icd-loader is installed too.

Just today I built and installed a completely fresh build of wine-vulkan from my AUR package and I can say that the current version still works, so it's most likely an issue with the configuration.

**Comment by sajmonella9** [comment]
Ok working.... lol don't believe!

**Comment by sajmonella9** [comment]
Game stared but it's blackscreen. Running by : 
`DXVK_LOG_LEVEL="debug" DXVK_SHADER_DUMP_PAH="./shaders" DXVK_SHADER_READ_PATH="./optimized" DXVK_SPIRV_OPT_PATH="./wine/drive_c/VulkanSDK/1.0.68.0/Bin/spirv.exe" DXVK_HUD="1" wine "DIR/TO/GAME/Steam.exe"`
But this time game was started without problem.

**Comment by Yardanico** [comment]
@sajmonella9 did you install `spirv-tools` through pacman?

**Comment by sajmonella9** [comment]
From Terminal: 

`IPC client is in my process, could/should be using an in-process pipe.IPC client is in my process, could/should be using an in-process pipe.Setting breakpad minidump AppID = 368070
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198342061810 [API loaded no]
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  D3D11CreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
warn:  Vulkan extension VK_KHR_maintenance2 not supported
info:  Enabled device extensions:
info:    VK_KHR_maintenance1
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
warn:  DxbcOptions: Growing coordinate vector for Dref operations
warn:  DxbcOptions: Using FMin/FMax/FClamp instead of NMin/NMax/NClamp
info:  Enabled instance layers:
info:  Enabled instance extensions:
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  D3D11CreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
warn:  Vulkan extension VK_KHR_maintenance2 not supported
info:  Enabled device extensions:
info:    VK_KHR_maintenance1
info:    VK_KHR_shader_draw_parameters
info:    VK_KHR_swapchain
warn:  DxbcOptions: Growing coordinate vector for Dref operations
warn:  DxbcOptions: Using FMin/FMax/FClamp instead of NMin/NMax/NClamp
warn:  DxgiDevice::SetMaximumFrameLatency: Stub
err:   DxgiOutput::FindClosestMatchingMode: Not implemented
err:   DxgiOutput::FindClosestMatchingMode: Not implemented
warn:  DxgiFactory::MakeWindowAssociation: Ignoring flags
err:   DxgiAdapter::CheckInterfaceSupport: No D3D10 support
err:   DxgiAdapter: No format mapping for DXGI_FORMAT_R1_UNORM
info:  DxgiPresenter: Recreating swap chain: 
  Format:       VK_FORMAT_B8G8R8A8_UNORM
  Present mode: VK_PRESENT_MODE_FIFO_KHR
  Buffer size:  1920x1080
`
Nope i don't install that package from pacman, i linked from VulkanSDK installer. Inside of my wine. Normal .exe file.

**Comment by Yardanico** [comment]
@sajmonella9 well then your game doesn't yet work with dxvk

**Comment by sajmonella9** [comment]
If you're sure. It went fast. In that case, thank you all for help :).

**Comment by pchome** [comment]
@sajmonella9 
> DXVK_SPIRV_OPT_PATH=

Are you sure ?

**Comment by doitsujin** [comment]
Closing this since most of what was being discussed here was a setup issue.
