### ISSUE TITLE
[d3d9] Mafia II: Missing shadows under vehicles, characters and objects (depth bias)

### ISSUE THREAD

**Issue by HunterCZ122** [doitsujin/dxvk#1294]
**D9VK**
http://www.img.tpx.cz/uploads/d9vk.png
http://www.img.tpx.cz/uploads/d9vk1.png
http://www.img.tpx.cz/uploads/d9vk2.png

**Native DX9**
http://www.img.tpx.cz/uploads/dx9.png
http://www.img.tpx.cz/uploads/dx91.png
http://www.img.tpx.cz/uploads/dx92.png

### Software information
Mafia II Steam version, max settings without PhysX and antialiasing.
Also occurs on Proton 4.11 when I had Manjaro Linux partition.
WineD3D works fine (except for flickering sky).

### System information
- GPU: NVIDIA GeForce GTX 1660 Ti
- Driver: 441.71.0 (Windows)
- DXVK version: v1.5-12-g3c8fdc2

### Apitrace file(s)
- https://drive.google.com/file/d/1M8mCGdqt-41hL1x9kezq-cZTLD1h-kqL/view?usp=sharing

### Log files
- d3d9.log: [mafia2_d3d9.log](https://github.com/doitsujin/dxvk/files/3980713/mafia2_d3d9.log)

**Comment by Joshua-Ashton** [comment]
This is already known and is depth bias.

**Comment by Joshua-Ashton** [comment]
This should be fixed now.

**Comment by HunterCZ122** [comment]
Unfortunately, it isn't fixed.
![M2](https://user-images.githubusercontent.com/23011428/73128680-46669a00-3fd3-11ea-8cf6-e08d6052f3c6.png)

**Comment by Joshua-Ashton** [comment]
Fixed!
