### ISSUE TITLE
[d3d9] Final Fantasy 9 crashes at launch with DXVK 1253+

### ISSUE THREAD

**Issue by NerosTie** [doitsujin/dxvk#1571]
Title.

It works with 1252 and less.

Precision: I don't launch the game from the launcher, directly with FF9.exe (x64). The issue doesn't come from the launcher.

This is the error message:

![Screenshot_20200415_142220](https://user-images.githubusercontent.com/4572452/79336739-88451380-7f24-11ea-9a34-d15ae159fd0e.png)

Crash reports from the game itself:

[error.log](https://github.com/doitsujin/dxvk/files/4481131/error.log)
[output_log.txt](https://github.com/doitsujin/dxvk/files/4481132/output_log.txt)

Option in Steam to launch the game (from protondb):
`set -- %command%; "${@:1:2}" x64/FF9.exe "${@:4}"`

### System information
- GPU: Nvidia Geforce 730M
- Driver: nvidia-vulkan 440.66.08
- Wine version: Proton 5.0-5
- DXVK version: 1253 and 1254

### Apitrace file(s)
https://mega.nz/file/v3hUAITT#23Fe7RRU5WfyxNz3wfM4R0YwB-guLiOwPXdQiH0oCG4

### Log files
[steam-377840-dxvk.log](https://github.com/doitsujin/dxvk/files/4481180/steam-377840-dxvk.log)

**Comment by doitsujin** [comment]
Which commit is 1253 exactly?

**Comment by NerosTie** [comment]
It's 1253 from https://git.froggi.es/doitsujin/dxvk/-/jobs

But it's down, so I can't answer more precisely :/

**Comment by doitsujin** [comment]
Yeah, that's why I was asking. Any chance you can build yourself and bisect the problem?

I guess Josh can take a look later, but in general it's much more useful to refer to commits than to build numbers (I *think* they should be displayed on the froggi.es website when it's up).

**Comment by tannisroot** [comment]
@NerosTie can you tell us the commit hash number by running any app (even d3d11 one) with that build with DXVK_HUD=version envar and and screenshoting the game screen (it will show the hash in the hud along with dxvk version).

**Comment by doitsujin** [comment]
@tannisroot that doesn't work when the game literally crashes.

@NerosTie can you please upload your DXVK build somewhere? I think we can infer the commit from that.

**Comment by tannisroot** [comment]
@doitsujin whoops, i meant any unaffected app. For example, this d3d9 triangl test app should work:
[d3d9-triangle.zip](https://github.com/doitsujin/dxvk/files/4482659/d3d9-triangle.zip)

**Comment by doitsujin** [comment]
Thanks; looks like 4699d4162a36ee26eb03346eccd5ab1f48168466 broke it then.

**Comment by Berobad** [comment]
Something similar happens with Guild Wars 2 since commit 4699d41 with RADV 
Testet my own builds with both mingw 9.2 and 9.3 and tested the built from froggi.es.

![gw2_crash_dxvk_4699d41](https://user-images.githubusercontent.com/10475553/79393282-5019f100-7f75-11ea-8add-8de7f445d964.png)

**Comment by Berobad** [comment]
At least for Guild Wars 2 the #1577 does seem to fix it.

**Comment by Joshua-Ashton** [comment]
Please re-test, this should be fixed in `master`.

**Comment by Berobad** [comment]
Guild Wars 2 does crash again with your fixes

**Comment by NerosTie** [comment]
@Joshua-Ashton 
It is no longer possible to download packages on froggi.es? (it's asking me to login)

(I compiled it and the issue is not fixed)

**Comment by Joshua-Ashton** [comment]
Can you try now

**Comment by logan001** [comment]
just as info GW2 finally stop crashing.

**Comment by NerosTie** [comment]
Fixed! Thanks :)
