### ISSUE TITLE
[d3d9] Duke Nukem Forever → the shadows are not "soft"

### ISSUE THREAD

**Issue by NerosTie** [doitsujin/dxvk#1641]
With DXVK:
![Screenshot_20200525_210441](https://user-images.githubusercontent.com/4572452/82840532-3e602d80-9ed3-11ea-87a6-d1ff06e4e8a8.png)

With WineD3D:
![Screenshot_20200525_210308](https://user-images.githubusercontent.com/4572452/82840542-44eea500-9ed3-11ea-8ce2-b121a332004e.png)

It's not the same bug as https://github.com/doitsujin/dxvk/issues/1639, it would be like this instead:
![Screenshot_20200525_210700](https://user-images.githubusercontent.com/4572452/82840566-5768de80-9ed3-11ea-96d8-af89b4d5353c.png)

### System information
- GPU: Nvidia GeForce GT 730M
- Driver: nvidia-vulkan 440.66.14
- Wine version: Proton 5.0
- DXVK version: 1297

### Apitrace file(s)
https://mega.nz/file/yzYXDQha#tSJKWoMY2xDloDO-6RkSKUanxKk_CA8yz7yIx-Vrjb4

### Log files
[steam-57900-wined3d.log](https://github.com/doitsujin/dxvk/files/4678677/steam-57900-wined3d.log)
[steam-57900-dxvk.log](https://github.com/doitsujin/dxvk/files/4678676/steam-57900-dxvk.log)

**Comment by CME42** [comment]
The trace is working fine and it seems like DF24 is not being used, so i guess this was created with wined3d, can you record one with dxvk?

**Comment by Joshua-Ashton** [comment]
The order/swizzle on my FETCH4 might be incorrect -- but thats an easy fix if I can get a trace to figure that out.

**Comment by NerosTie** [comment]
Here it is! 

https://mega.nz/file/z2AR1Q4K#q59hYHn710svdelHsXvnqs2kbTBF95LfY7F0K1gRkxk

(sorry, I'm late)

**Comment by Joshua-Ashton** [comment]
Should be fixed now :)

**Comment by NerosTie** [comment]
It's way better! 

But when I look closer, the issue is still here:

dxvk:
![Screenshot_20200527_103503](https://user-images.githubusercontent.com/4572452/82997034-250bce00-a006-11ea-8682-b75c75075598.png)

wined3d:
![Screenshot_20200527_103655](https://user-images.githubusercontent.com/4572452/82997052-2b9a4580-a006-11ea-90a9-de8f7b598e35.png)

**Comment by Joshua-Ashton** [comment]
Can you try reverting 2fc00a331b952b1ecba9813d892f1edf80688c68? Otherwise at this point I do not know :<

**Comment by Joshua-Ashton** [comment]
also if you can can you provide a trace close up with DXVK so I can check it against AMD native? It could just be like that...

**Comment by NerosTie** [comment]
Nope, it's the same thing as the first screenshot:

![Screenshot_20200527_104419](https://user-images.githubusercontent.com/4572452/82997762-1a9e0400-a007-11ea-8709-d62d783b18ca.png)

I think you have to reopen the issue 🤷

**Comment by Joshua-Ashton** [comment]
(fudge it to use

**Comment by Joshua-Ashton** [comment]
can you provide a trace close up with DXVK so I can check it against AMD native? It could just be like that...

if it is, then i can fudge it to use the path it does in wined3d

**Comment by NerosTie** [comment]
https://mega.nz/file/Kv43ETyA#zGaL3S09AHMZ5v6pM8A4v2za48RWRsTkSpcOjQYEUwA

**Comment by Joshua-Ashton** [comment]
Should be fixed for good now :)

**Comment by NerosTie** [comment]
Again, it's better!

BUT (I know..) there is still a difference with wined3d:

With wined3d, you have a lot of "noise":
![Screenshot_20200527_134931](https://user-images.githubusercontent.com/4572452/83015747-32828180-a021-11ea-910a-2a19557e4ffc.png)

Which is not here with dxvk:
![Screenshot_20200527_135046](https://user-images.githubusercontent.com/4572452/83015791-429a6100-a021-11ea-867c-b70205151cc1.png)

Plus, you can notice there are black lines we shouldn't see.

**Comment by doitsujin** [comment]
iirc the game uses a different method to sample shadows on dxvk compared to wined3d, so differences are expected.

**Comment by Joshua-Ashton** [comment]
If you can get a dxvk trace super up close I can validate that on native and see if anything is amiss. Sorry to be a pain

**Comment by NerosTie** [comment]
https://mega.nz/file/rn4jwbTB#K7c9HP8ndCIgsp3qjhRMr7Jv7SyBFgf5tkAcJAfsD-w

(sorry, it's very long to upload at home)

**Comment by NerosTie** [comment]
Can this issue be reopened?

**Comment by Joshua-Ashton** [comment]
This should be fixed now 👍

**Comment by NerosTie** [comment]
The black bars are gone!

But he "noise" is still not here:

WINED3D:
![Screenshot_20200601_144510](https://user-images.githubusercontent.com/4572452/83410350-853fad00-a416-11ea-9dfb-208d135e9041.png)

DXVK:
![Screenshot_20200601_144437](https://user-images.githubusercontent.com/4572452/83410302-6c36fc00-a416-11ea-9939-062b4db72a1b.png)
 
Which one is supposed to be the right one?

**Comment by Joshua-Ashton** [comment]
Its a different shadow path.

**Comment by NerosTie** [comment]
What's does it mean? Is the "noise" not being here normal?

**Comment by Joshua-Ashton** [comment]
For the shadow path on AMD, yes.

**Comment by NerosTie** [comment]
But I have a Nvidia GPU.

**Comment by K0bin** [comment]
It's using D3D9 driver hacks that Nvidia usually doesn't have.

**Comment by NerosTie** [comment]
Buy I have this "noise" with my Nvidia GPU with WINED3D. Why not with DXVK? I don't understand :/

**Comment by Joshua-Ashton** [comment]
Because we expose DF24 which uses a different shadow path.

**Comment by NerosTie** [comment]
I guess everything's normal then.

Let's say Duke Nukem Forever is... done™

**Comment by K0bin** [comment]
Duke Nukem Forever has two different ways to filter shadows:
With DXVK the game uses the one primarily built for AMD GPUs. That is because DXVK supports D3D9 driver hacks that typically Nvidia's Windows D3D9 driver doesn't support. DXVK also supports those on Nvidia GPUs.
When those hacks (DF24 in particular here) aren't present (as would be the case on Nvidia Windows D3D9 drivers), the game does something else to filter shadows.
