### ISSUE TITLE
[Windows 10][AMD][D3D9] Dogfight 1942; Graphical Artifacts, black squares, flickering white blobs

### ISSUE THREAD

**Issue by springwurm** [doitsujin/dxvk#2186]
Hello,

This game has some issues, both on Windows and Linux.

### Software information
- Name: Dogfight 1942
- Settings: All Max

### System information
- GPU: AMD Radeon RX 570
- Driver: 2.0.179
- OS: Windows 10

### Apitrace file(s)
- [Dogfight1942_windows_10_dxvk1.9_iwo_jima.trace.tar.xz](https://mega.nz/file/GIVXkKwI#P-_weaHuLtPcDeYIHbmba0S-A3Ubry51y63RdmLZq4c)
- [Dogfight1942_windows_10_dxvk1.9_midway.trace.tar.xz](https://mega.nz/file/6QN1EKaD#N-CmSOqms-dzJ0orszDf3Sxx64sFdMJEEceG0rjdvcA)

### Screen Recordings
- [Dogfight1942_windows_10_dxvk1.9_iwo_jima.mp4](https://mega.nz/file/TEcXUKAY#VTQNazXCQu1G4Z9JCZruIMEnm5IqCp5HnV1ZwUxOsMo)
- [Dogfight1942_windows_10_dxvk1.9_midway.mp4](https://mega.nz/file/eRVFzCxa#QwPeP-zZE-_5qQVLViOG7icaN3z8YSFVlpt-YmfiSVM)

### Log files
- [Dogfight1942_d3d9_windows_10_dxvk1.9.log](https://github.com/doitsujin/dxvk/files/6876119/Dogfight1942_d3d9_windows_10_dxvk1.9.log)

### Note
- Happens on Linux with Proton too. See: https://github.com/ValveSoftware/Proton/issues/3910
- I played a bit with the Game Settings, but no luck.

**Comment by Evernow** [comment]
Cannot reproduce on my NVIDIA system.

**Comment by CME42** [comment]
The game is multiplying inf by some number in a fragment shader which results in NaN. So it's the same issue as #1619 .

**Comment by K0bin** [comment]
Should be fixed by c13395db970d16a5631a7c0926e2c4529d2710c3

**Comment by springwurm** [comment]
> Should be fixed by [c13395d](https://github.com/doitsujin/dxvk/commit/c13395db970d16a5631a7c0926e2c4529d2710c3)

Thanks, but on the "Iwo Jima" Map the artifacts are still present.

Midway: looks good.
![20211212113900_1](https://user-images.githubusercontent.com/65482005/145872928-0a9bb316-9c50-4fd0-91c4-35de57b446e3.jpg)

Iwo Jima:
![20211212113345_1](https://user-images.githubusercontent.com/65482005/145873033-13079cdd-25d8-4cf5-82ad-d1d8fdea53ec.jpg)

**Comment by Joshua-Ashton** [comment]
Does `RADV_DEBUG=nodcc` fix those?

**Comment by springwurm** [comment]
> Does `RADV_DEBUG=nodcc` fix those?

Sorry for the late reply, but i wasn't able to test this option. At the moment i can´t get the game running with Wine/Proton (i tried several versions), it looks like there is some regression.

**Comment by springwurm** [comment]
> is this still an issue with 1.10.1?

no, it's fine now. Thanks

![20220330110136_1](https://user-images.githubusercontent.com/65482005/160804333-9b136a8e-d780-490c-a147-3cf1df0fde92.jpg)
