### ISSUE TITLE
World of Warships crashes when MSAA is enabled

### ISSUE THREAD

**Issue by AccountOneOff** [doitsujin/dxvk#227]
Game boots fine but crashes if Reflections are enabled.

### Software information
World of Warships
High preset

### System information
- GPU: GTX 960
- Driver: 390.48
- Wine version: Staging 3.4
- DXVK version: 6babc22

### Apitrace file(s)
- Pending. Runs with wined3d but crashes with apitrace. 
- [WorldOfWarships-apitrace-crash.zip](https://github.com/doitsujin/dxvk/files/1864979/WorldOfWarships-apitrace-crash.zip)

### Log files
- d3d11.log: [worldofwarships_d3d11.log](https://github.com/doitsujin/dxvk/files/1864849/worldofwarships_d3d11.log)

- dxgi.log: [worldofwarships_dxgi.log](https://github.com/doitsujin/dxvk/files/1864851/worldofwarships_dxgi.log)

[screenshot from 2018-03-30 14-48-29](https://user-images.githubusercontent.com/15083452/38155000-0c172984-342a-11e8-9ee5-839e02c4c4cb.png)

**Comment by doitsujin** [comment]
Thanks for narrowing down which setting causes the issue. MSAA causes crashes as well, without those options, I can at least get into the port.

I can reproduce the crash and I already have an apitrace of the game with reflections enabled, but replaying that freezes my GPU even before the trace reaches the login screen, not sure how to debug this.

**Comment by doitsujin** [comment]
Fixed in e06300d592f17ade25511e4f92a679192f1d8df3, reflections should render fine now. Please test whether MSAA works on your end, on RADV it causes a GPU hang.

**Comment by AccountOneOff** [comment]
Reflections are working with that commit but MSAA still crashes it.

**Comment by doitsujin** [comment]
MSAA issues should be fixed in 5cb65a6c19049f7f48c0833e0c694c0641015be9.

**Comment by AccountOneOff** [comment]
It still crashes with that commit.

**Comment by doitsujin** [comment]
It works on RADV. Please run with
```
export DXVK_LOG_LEVEL=debug
```

**Comment by AccountOneOff** [comment]
Here you go:

[worldofwarships_d3d11.log](https://github.com/doitsujin/dxvk/files/1896380/worldofwarships_d3d11.log)
[worldofwarships_dxgi.log](https://github.com/doitsujin/dxvk/files/1896381/worldofwarships_dxgi.log)

**Comment by doitsujin** [comment]
Can you test if it works with the current Nvidia beta driver? It might not render correctly due to regressions in their new compiler (see #267), but let me know if it still crashes and if there are `err:   Failed to create graphics pipeline`-like errors in the DXVK logs.

**Comment by AccountOneOff** [comment]
No longer crashes, however, it did hang once I got in a match. I don't see any `err:` in the logs either.

[worldofwarships_d3d11.log](https://github.com/doitsujin/dxvk/files/1908584/worldofwarships_d3d11.log)
[worldofwarships_dxgi.log](https://github.com/doitsujin/dxvk/files/1908585/worldofwarships_dxgi.log)

**Comment by doitsujin** [comment]
Does that hang happen when you play using the old shader compiler (with MSAA disabled)?

I noticed after playing for a while that my dmesg is spammed with VM faults, so there's probably still something wrong on the DXVK side of things (although the game actually runs fairly well on RADV).

**Comment by AccountOneOff** [comment]
Doesn't hang when the compiler is disabled.
