### ISSUE TITLE
Pathfinder: Wrath of the Rightous freezes in some loading screens

### ISSUE THREAD

**Issue by mkalte666** [doitsujin/dxvk#2286]
In some areas in the game (namely, third floor of the gray garrison) the game freezes in the loading screen. 
It must be killed (via steams stop button or command line). 
The issue also occurs if you load a save that is in said location.

I have thrown current master (as of writing this) into the games proton prefix and could still replicate the error. See the logs below. 

Note that the issues does not occuur if i set PROTON_USE_WINED3D=1.
 

### Software information
Pathfinder: Wrath of the Rightous. 
I have tried this on multiple graphics settings (fullscreen, borderless window, window, multiple quality settings). 

### System information
- GPU: NVIDIA GeForce GTX 980 Ti
- Driver:470.63.01
- Wine version: 6.16 (staging)
- DXVK version: master (827c7a892ca399fd1ddda3051ee51f7b59af2cdd)

### Apitrace file(s)
I should not be surprised that the files are huge. 
This is the last bit i can see, but i will throw an upload on as soon as im not blocking the whole flats internet doing so and provide a link. 
https://i.imgur.com/LNHDj0U.png

EDIT: https://mkalte.me/share/public/Wrath.trace.tar.gz

### Log files
Put them in a gist here: https://gist.github.com/mkalte666/04061f2074252c19f8708adfebe1ef17

**Comment by doitsujin** [comment]
Does it actually freeze or is it just compiling a metric arsetonne of shaders?

**Comment by mkalte666** [comment]
> Yeah, driver crash.

    sudo dmesg 
    [...]
    [24210.679811] NVRM: Xid (PCI:0000:26:00): 8, pid=2826, Channel 0000005b
    [24322.296885] NVRM: Xid (PCI:0000:26:00): 8, pid=4165, Channel 0000005b
    [25048.319677] NVRM: Xid (PCI:0000:26:00): 8, pid=8128, Channel 0000005b
    [30189.871206] NVRM: Xid (PCI:0000:26:00): 8, pid=26819, Channel 0000002b


Oh well.. thanks for having a look. 
Trace is uploading.

**Comment by mkalte666** [comment]
Trace is here. https://mkalte.me/share/public/Wrath.trace.tar.gz

I cant get vulkan validation layers to work when launching from within steam, or i would check if anything happens there as well.

**Comment by doitsujin** [comment]
I can't connect to the server for some reason.

Getting Vulkan validation to work is a mess since the new Steam runtime got introduced, so yeah, don't bother with that.

**Comment by mkalte666** [comment]
> I can't connect to the server for some reason.

Woops sorry, should work now. forgot to restart it

**Comment by doitsujin** [comment]
Hm, trace replays fine here. Can you share a savegame so I can install the game and have a look?

**Comment by mkalte666** [comment]
If i try to replay the trace, qapitrace.exe crashes for me. let me see if i can get something out of that. 

Save file: https://mkalte.me/share/public/Quick_3.zks
Put here: `[...]/steam/steamapps/compdata/1184370/pfx/drive_c/users/steamuser/AppData/LocalLow/Owlcat Games/Pathfinder Wrath Of The Righteous/Saved Games`

**Comment by mkalte666** [comment]
Jap i can reliably reproduce it using the trace. 

Output of 
`DXVK_LOG_LEVEL=debug VK_LAYER_PATH=/usr/share/vulkan/explicit_layer.d/ VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation WINEPREFIX="/media/fastGames/STEAM/steamapps/compatdata/1184370/pfx/" wine /tmp/apitrace-10.0-win64/bin/d3dretrace.exe /media/fastGames/STEAM/steamapps/compatdata/1184370/pfx/drive_c/users/steamuser/Desktop/Wrath.trace > d3dretrace.log 2>&1 
` 

is here: https://mkalte.me/share/public/d3dretrace.log

**Comment by mkalte666** [comment]
I can confirm that this patch fixes the issue for me. Thanks for putting in the work and putting up with me!

**Comment by crabel** [comment]
Thanks, I can also confirm that the issue is fixed with this commit. Thank you!

**Comment by t3hbunbun** [comment]
I report that this patch did not fix the issue for me. I got through one loading screen, played through the area (drezen before chapter 3), and as I try to load into chapter 3, the same loading screen crash persists. With this patch X11 does not glitch out but the game is still unplayable.

**Comment by doitsujin** [comment]
That's a different issue and most likely a game bug. Players have been reporting this on Windows as well.
