### ISSUE TITLE
Medieval 2 black loading screen

### ISSUE THREAD

**Issue by boludoz** [doitsujin/dxvk#2427]
This makes a black screen and exit when fighting against armies in battle mode, it also makes a black screen every time it loads and only the loading bar appears. I was very happy because the game runs at about 400 fps faster than DX9 and they recently fixed the map problems.

### Software information
Medieval 2: Total War

### System information
- GPU: GTX 1070
- Driver: 497.29
- Wine version: Windows 11
- DXVK version: dxvk-1.9.2

### Apitrace file(s)
error: failed to find d3d9.dll wrapper (rerun with -v option for more details) and this delete my d3d9.dll (And appears access deniend to artifact)

### Log files
- d3d9.log: [medieval2_d3d9.log](https://github.com/doitsujin/dxvk/files/7824828/medieval2_d3d9.log)
- d3d11.log: - 
- dxgi.log: -

Savegame of battle:
[Turquito.zip](https://github.com/doitsujin/dxvk/files/7824878/Turquito.zip)

Settings:
Tested game in 1080p and 4k.

[medieval2.preference.zip](https://github.com/doitsujin/dxvk/files/7824881/medieval2.preference.zip)

**Comment by DadSchoorse** [comment]
The crash when loading battles was already reported and fixed in #2264. Try master. Github Action has up to date builds if you need one https://github.com/doitsujin/dxvk/suites/4719763182/artifacts/129743674 .

**Comment by boludoz** [comment]
[medieval2_d3d9.log](https://github.com/doitsujin/dxvk/files/7867715/medieval2_d3d9.log)
The game closes when exiting the battle

**Comment by DadSchoorse** [comment]
Battles are working fine for me.
Can you tell me what I have to do to reproduce the issue?

**Comment by K0bin** [comment]
Could still be address space woes, especially given that the boludoz is using Windows.

**Comment by boludoz** [comment]
> Battles are working fine for me. Can you tell me what I have to do to reproduce the issue?

It happens in defenses or in battles when you come out of the battle having won or lost, this normally doesn't happen, I use Windows because I really like the performance that DXVK brings to older games.

**Comment by Blisto91** [comment]
I can reproduce the black background on loading screens, but not the crash on battle exit.

Is this still a issue with the lastest driver and dxvk?

Tested on Win10 Geforce 960 with latest driver and dxvk 1.9.3

**Comment by Blisto91** [comment]
I also see the black loading background when using amd mesa.

I tried to record a trace on windows without dxvk and thought it would show when i replayed on linux with dxvk installed on wine, but there it shows fine. (Maybe i misunderstand how i should make the trace or how it replayes)
But if i make a apitrace on linux through proton i can see it in the replay.
Tho the OP has the issue on windows when using dxvk.

Trace on native windows.
https://mega.nz/file/g0ZQwIpR#BI5Xti3prgaL734LBsbGBJZEezLZfAYNtz3XghQKOx8

Trace on linux proton dxvk.
https://mega.nz/file/BxBGQDrb#h6aVjwNRLmnKWaPLctQak7b7X9kLj1q3VaFJuLn9-Oc

**Comment by Blisto91** [comment]
@boludoz For the crashes try to test K0bin's new PR and see if it helps https://github.com/doitsujin/dxvk/pull/2663
Link to latest version as of this moment: https://github.com/doitsujin/dxvk/actions/runs/2480480782

**Comment by K0bin** [comment]
This is another case of #1318. I'm gonna close this because we're already aware of the problem and tracking it in that other issue.

**Comment by Blisto91** [comment]
The missing loading screen graphics is also a issue

**Comment by Blisto91** [comment]
The Black loading screen bug in medieval 2 can also sometimes happen on windows if I'm reading this correctly. There it seems to have something to do with resolution. 
Might be a clue.

https://www.twcenter.net/forums/showthread.php?683758-Loading-screen-glitch

https://steamcommunity.com/app/4700/discussions/0/385429254932423059/

**Comment by Blisto91** [comment]
Black loading screen has been fixed in 1.10.2

**Comment by EddieEldridge** [comment]
> Black loading screen has been fixed in 1.10.2

![image](https://github.com/doitsujin/dxvk/assets/22448079/a365d0a3-5275-4bdc-871a-80ede065fe5d)

I'm still seeing this in 2.2

**Comment by Blisto91** [comment]
@EddieEldridge Hi there. I don't seem to be reproducing (tested on Windows while i was there).
What is your resolution?

**Comment by EddieEldridge** [comment]
> @EddieEldridge Hi there. I don't seem to be reproducing (tested on Windows while i was there).
> What is your resolution?

2560x1080 monitor
1920x1080 game (borderless_window)

It doesn't happen with dxvk 😕

**Comment by Blisto91** [comment]
Ye i just noticed the window mode after i wrote. Can reproduce with that.

**Comment by EddieEldridge** [comment]
> Ye i just noticed the window mode after i wrote. Can reproduce with that.
> 
> Edit: Made a new issue #3724

Thanks for looking into it and making the issue. Glad it's nothing major!
