### ISSUE TITLE
Spellforce 3 Crashes with DxvkBufferView::DxvkBufferView: Failed to create buffer view

### ISSUE THREAD

**Issue by xpander69** [doitsujin/dxvk#274]
Launching the game causes it to crash instantly after the window is drawn.
Game creates a dmp file also.

Same error with both new and old compiler of the 396.18 drivers

### Software information
Spellforce 3

### System information
- GPU: GTX 1070
- Driver: 396.18
- Wine version: 3.5 staging
- DXVK version: 8508994

### Log files
- d3d11.log:
[SF3ClientFinal_d3d11.log](https://github.com/doitsujin/dxvk/files/1906795/SF3ClientFinal_d3d11.log)

- dxgi.log: 
[SF3ClientFinal_dxgi.log](https://github.com/doitsujin/dxvk/files/1906797/SF3ClientFinal_dxgi.log)

Games own dmp file if thats even usable:

[SF3Client_2018_04_13_12_44_27_REV_45405.dmp.tar.gz](https://github.com/doitsujin/dxvk/files/1906802/SF3Client_2018_04_13_12_44_27_REV_45405.dmp.tar.gz)

**Comment by doitsujin** [comment]
Sounds like a similar issue to the one @ZeroFault reported for AC:Origins. I'll add some more debug output later to see what's going on.

**Comment by doitsujin** [comment]
Please re-run with 15fca0b0b1fc9446f2f8eb2402218d0c407c4de5.

**Comment by xpander69** [comment]
Tested, now i get a bit more output on that:

```
info:  D3D11CreateDevice: Probing D3D_FEATURE_LEVEL_11_0
info:  D3D11CreateDevice: Using feature level D3D_FEATURE_LEVEL_11_0
err:   DxvkPhysicalBufferView: Failed to create buffer view:
  Offset: 0
  Range:  353894400
  Format: VK_FORMAT_R32_UINT
err:   DxvkPhysicalBufferView: Failed to create buffer view:
  Offset: 0
  Range:  353894400
  Format: VK_FORMAT_R32_UINT
```

still crashes at after window drawing

**Comment by pdaniell-nv** [comment]
This should be fixed with 396.18.05, which can be found here: https://developer.nvidia.com/vulkan-driver.

**Comment by xpander69** [comment]
Thanks.  Seems to still crash, but not a bufferview issue anymore

[SF3ClientFinal_d3d11.log](https://github.com/doitsujin/dxvk/files/1948773/SF3ClientFinal_d3d11.log)
[SF3ClientFinal_dxgi.log](https://github.com/doitsujin/dxvk/files/1948775/SF3ClientFinal_dxgi.log)
