### ISSUE TITLE
[d3d9] Grand Theft Auto IV - ingame light sources flicker

### ISSUE THREAD

**Issue by TacoDeBoss** [doitsujin/dxvk#2954]
In Grand Theft Auto IV, ingame light sources will flicker at certain camera angles when the graphics option Night Shadows is enabled.
The apitrace also reproduces the issue on wined3d, so I'm not convinced this is strictly a DXVK bug per se, but to my knowledge this doesn't happen on Windows d3d9 drivers.

### Software information
Grand Theft Auto IV: The Complete Edition ([Steam appid 12210](https://store.steampowered.com/app/12210/Grand_Theft_Auto_IV_The_Complete_Edition/))

### System information
- GPU: Radeon RX 5700 XT
- Driver: Mesa 22.1.7
- Wine version: Proton 7.0-4
- DXVK version: 1.10.3

### Apitrace file(s)
- [GTAIV.trace.tar.gz](https://drive.google.com/file/d/1Yyit2gS8S83UxaxPG_crCltf1bxKykuM/view?usp=sharing)

**Comment by TacoDeBoss** [comment]
I decided to install Windows, and lo and behold, I can also reproduce on native drivers too. It looks like it's definitely just a game bug. Too bad...

**Comment by pchome** [comment]
Fixable. It either depend on nvapi, `d3d9.supportDFFormats = False` dxvk option (fixed in current master and 1.10.x git branches), or maybe it was forced Mip LOD Bias (-1)
![gta-eflc mip-lod-bias-small](https://user-images.githubusercontent.com/10661854/192010203-6081f17b-61f1-4b68-986f-788ad7c748dd.png)

**Comment by TacoDeBoss** [comment]
> Fixable. It either depend on nvapi, `d3d9.supportDFFormats = False` dxvk option (fixed in current master and 1.10.x git branches), or maybe it was forced Mip LOD Bias (-1)

Can you elaborate? I'm using AMD hardware here so I doubt nvapi stuff would help, but regardless I tested on a GTX 1070 with native nvapi and the bug was still happening. `d3d9.supportDFFormats = False` doesn't make a difference, master builds are the same, and I'm not sure how to force Mip LOD Bias? I saw something like that for d3d11 in dxvk.conf, but nothing about d3d9.

**Comment by pchome** [comment]
[libstrangle](https://gitlab.com/torkel104/libstrangle) can do via `STRANGLE_PICMIP=-1` environment variable or via launcher script with parameter.
