### ISSUE TITLE
Lost Sphear no sprites / freeze in the beggining

### ISSUE THREAD

**Issue by caiot5** [doitsujin/dxvk#406]
The game launches with no sprites at all, I can see the backgrounds, the spells but there's no NPC, no Characters and etc.
After the intro, it hangs (with the music playing normally at the background) when the main character supposed to wake in his bed.

### Software information
LOST SPHEAR 
Any Setting

### System information
- GPU: GeForce GTX1050Ti
- Driver: 396.24
- Wine version: 3.7
- DXVK version: 0.53-1

### Apitrace file(s)
- I could not manage to "install" APITRACE

### Log files
- d3d11.log: http://ybshare.com/download/6nb5vzrvqn
- dxgi.log: http://ybshare.com/download/ru1aymqw8j

**Comment by doitsujin** [comment]
The game requires Stream Output (#135), which is likely the cause of the rendering issues. It's a common thing with Unity Engine games.

Also there seems to be a small issue with some of the vertex shaders:
`warn:  DxbcCompiler: Unhandled VS SV output: DxbcSystemValue::RenderTargetId`

**Comment by doitsujin** [comment]
> So are you sure is it related to stream output ?

No, but it's an educated guess. If it still doesn't work after Stream Output is implmented, it'll make sense to look into this issue further, but not before since issues are to be expected. The wined3d issue could be unrelated.

**Comment by caiot5** [comment]
I see.
Well, I would be happy to be test it when it's ready.
Let me know (just reply this post) and I can test it again.

Thank you!

**Comment by doitsujin** [comment]
9ff17b03f24c7a5d0a1825214f1697e5f6e48f1e should fix the shader compilation warnings, please let me know if this changes anything.

Wine doesn't support the extension so DXVK will likely complain about it, but you could give it a shot nonetheless.

**Comment by caiot5** [comment]
The game doesn't freezes anymore after the main character woke on his bed but it is still missing the sprites, there is no npc and no characters overall.

**Comment by doitsujin** [comment]
I suspect the lack of characters is due to Stream Output. I'll close this issue since that is already tracked in #135.
