### ISSUE TITLE
[d3d9] Scarface: The World Is Yours doesn't even boot with DVXK 2.4

### ISSUE THREAD

**Issue by Sagatt** [doitsujin/dxvk#4147]
### Software information
- **Name of the game:** Scarface: The World Is Yours
- **Settings used:** Default

### System information
- **GPU:** NVIDIA GeForce RTX 2060
- **Driver:** Latest NVIDIA driver (please specify version if known)
- **Operating System:** Windows 11
- **Wine version:** (Not applicable for Windows users)
- **DXVK version:** (Not applicable for Windows users)

### Apitrace file(s)
- None

### Log files

**Describe the issue:** Game doesn't even boot.

**Comment by Blisto91** [comment]
Please post dxvk logs and make a apitrace if able.

**Comment by mirh** [comment]
Does the version in the title imply that it was working for you with 2.3.1?

**Comment by koffiato** [comment]
Game gets stuck on black screen on my setup. Works fine with native DirectX 9, apitrace and logs are attached. Will try making the game run windowed as my monitor blacks out for a bit, the game may be changing exclusive fullscreen resolution in a funky way.

### System information
- GPU: AMD Radeon RX 6700 XT
- Driver: 24.6.1
- OS version: Windows 11 23H2
- DXVK version: 1.10.3, 2.3.1 and 2.4.0

### Apitrace file(s)
- [scarface.trace](https://drive.google.com/file/d/1ds-B596fqMRY9GRCS95S3fHbCz1wc7b_/view?usp=sharing)

### Log files
- [scarface_d3d9.log](https://github.com/user-attachments/files/16234887/scarface_d3d9.log)

**Comment by doitsujin** [comment]
If the log is anything to go by it locks up before even creating a swap chain, which is weird. Has this game *ever* worked with any version of DXVK?

Trace replays fine here, so there might be window message shenanigans going on perhaps, but not sure.

**Comment by Sagatt** [comment]
Never did work with any version at all, simply gives me a black screen.

**Comment by koffiato** [comment]
I tried going back to ancient versions with RADV driver, no dice; it never worked with DXVK. WINED3D works fine however.

**Comment by Blisto91** [comment]
Can you also post a apitrace where it doesn't work with dxvk. Might get something from comparing them

**Comment by K0bin** [comment]
The apitrace replays fine on my system as well. The fact that you cannot buy this game anymore, makes looking into this very problematic.

Blisto's idea was pretty good. Please try to make an apitrace with DXVK where the game crashes during recording of the trace.

**Comment by Sagatt** [comment]
But the game barely runs, literally the screen is blacked out

**Comment by koffiato** [comment]
@Blisto91 How do I do that exactly? Game boots into black screen and crashes whenever I click around. I tried putting `dxgitrace.dll` from apitrace along with `d3d9.dll` and `dxgi.dll` of DXVK next to the game executable; didn't work. Tried using `apitrace trace scarface.exe` but that also didn't create any trace files on desktop. In all of the cases, the game boots into black screen.

**Comment by Blisto91** [comment]
On Windows or Linux?

**Comment by koffiato** [comment]
Oh, sorry, I tried taking apitraces on Windows.

**Comment by Blisto91** [comment]
Put the apitrace `d3d9.dll` next to the game exe and the dxvk `d3d9.dll` in some folder you've created, where ever. Then in the Windows environment variable gui set `APITRACE_FORCE_MODULE_PATH` to the path of the folder with the dxvk dll. This will make apitrace use it instead of the system one.

**Comment by koffiato** [comment]
Thank you for the instructions. I started the game, waited a few minutes then force quit. The resulting [scarface.trace](https://github.com/user-attachments/files/16237530/scarface.zip) is just 2 bytes. Also tried running the apitrace with `-a d3d9` argument, same result; unable to replay.
![image](https://github.com/user-attachments/assets/fa3ad077-3896-4b05-8b20-fc02486bf6e0)

**Comment by Sagatt** [comment]
> If the log is anything to go by it locks up before even creating a swap chain, which is weird. Has this game _ever_ worked with any version of DXVK?
> 
> Trace replays fine here, so there might be window message shenanigans going on perhaps, but not sure.

Based on what you seen, what does that mean?

**Comment by Blisto91** [comment]
@koffiato thank you for the attempt but the trace with dxvk is sadly empty yes.
I have managed to find a cheap copy of the game so I should be able to give it a poke here next week.

**Comment by Sagatt** [comment]
> @koffiato thank you for the attempt but the trace with dxvk is sadly empty yes. I have managed to find a cheap copy of the game so I should be able to give it a poke here next week.

I could've just given you a copy bru

**Comment by Blisto91** [comment]
Apitrace from Windows with and without dxvk: https://drive.proton.me/urls/206PB23WP0#yAyK1z1Fq12Z

These are made with the game also using the SilentPatch but it freezes/crashes the same with dxvk on first frame.

**Comment by Sagatt** [comment]
Try using GangstaPatch, it's here on GitHub too

**Comment by niresh1234** [comment]
@K0bin @mirh @doitsujin @Blisto91 

Installing [D3D9 Wrapper by ThirteenAG](https://github.com/ThirteenAG/d3d9-wrapper) in game root

Replacing `d3d9.dll of DXVK` with `C:\Windows\SysWOW64\d3d9.dll`

**Its not solution but game works with DXVK....** and the wrapper repository available in GitHub

**Comment by Blisto91** [comment]
I'm not sure i understand what you mean

**Comment by niresh1234** [comment]
@Blisto91 the game not working with DXVK if install dxvk(d3d9.dll) in game root only, and shows only black screen...

but if install d3d9-wrapper also in the game.. then game work with DXVK..... but both have some .dll which is d3d9.dll..........

so I put and replace dxvk d3d9.dll in system folder

![Screenshot-(254)](https://github.com/user-attachments/assets/9b616afb-910c-4054-80d9-12834ac922cc)

**Comment by Blisto91** [comment]
You probably already know this but i am just going to put out a disclaimer to others.
### DO NOT REPLACE THE WINDOWS SYSTEM DLLS WITH DXVK UNLESS YOU KNOW WHAT YOU ARE DOING

But yes thanks. I assume it is working around the dxvk issue via windowed mode or some other tweaks.

**Comment by niresh1234** [comment]
> **Its not solution but game works with DXVK....**

Yes, I know.... Thats why I write [above](https://github.com/doitsujin/dxvk/issues/4147#issuecomment-2267513704)

**Comment by Sagatt** [comment]
> You probably already know this but i am just going to put out a disclaimer to others.
> ### DO NOT REPLACE THE WINDOWS SYSTEM DLLS WITH DXVK UNLESS YOU KNOW WHAT YOU ARE DOING. YOU'LL LIKELY BRICK YOUR INSTALL
> 
> But yes thanks. I assume it is working around the dxvk issue via windowed mode or some other tweaks.

This is a bad "solution".

**Comment by Blisto91** [comment]
No one has said it was a solution. The original issue stills stands ofc.

**Comment by mirh** [comment]
Unorthodox "chaining", but anything will do when grasping at straws I guess..
Can you track down [which option](https://github.com/ThirteenAG/d3d9-wrapper/blob/master/data/d3d9.ini) may be the fix?

**Comment by niresh1234** [comment]
@mirh @Blisto91 

`ForceWindowedMode = 1`  is working
(if set to 0, then game stuck at black screen)

**Comment by niresh1234** [comment]
@mirh @Blisto91 

`ForceWindowedMode = 1`  is working
(if set to 0, then game stuck at black screen)

Which is i noticed but not remember, I will check tomorrow again

**Comment by niresh1234** [comment]
`ForceWindowedMode = 1`  is working
(if set to 0, then game stuck at black screen)

Which is i noticed but not remember, I will check tomorrow again

**Comment by mirh** [comment]
I reckon you already tried to play with dxvk's *dpiAware*, *enableDialogMode*, and *deviceLossOnFocusLoss* options?

**Comment by niresh1234** [comment]
This is the only option used always `enableDialogMode`

**Comment by niresh1234** [comment]
@mirh I Try with this, but still black screen stuck
```
dxvk.hud=full
d3d9.enableDialogMode=True
d3d9.dpiAware=True
d3d9.deviceLossOnFocusLoss=True
```

& In D3D9-Wrapper, [This Line set to 1 is Working](https://github.com/ThirteenAG/d3d9-wrapper/blob/e6f4e506153f40b347bbbc301ca3c89e213517cd/data/d3d9.ini#L6) `ForceWindowedMode = 1`

**Comment by niresh1234** [comment]
@mirh I Try with this, but still black screen stuck
```
dxvk.hud=full
d3d9.enableDialogMode=True
d3d9.dpiAware=True
d3d9.deviceLossOnFocusLoss=True
```

& In D3D9-Wrapper, [This Line set to 1 is Working](https://github.com/ThirteenAG/d3d9-wrapper/blob/e6f4e506153f40b347bbbc301ca3c89e213517cd/data/d3d9.ini#L6) `ForceWindowedMode = 1`

**Comment by mirh** [comment]
My question was if you tried to toggle each of them, to see if anything changed. 
But I guess we already have some kind of lead. [Either](https://github.com/ThirteenAG/d3d9-wrapper/blob/d3d9-wrapper-v1.58/source/dllmain.cpp#L252) it's something with the screen dimensions or the window presentation parameters/styles?

You could try dxwrapper perhaps instead, to pinpoint this accurately (with the added benefit that AFAICT you [wouldn't need](https://github.com/elishacloud/dxwrapper/wiki/Configuration-(stub)#general) this wacky ass system dll hackjob to use dxvk together). Just remember to also set `EnableD3d9Wrapper=1` and then you have [endless](https://github.com/elishacloud/dxwrapper/wiki/Configuration-(advanced)#fullscreen) window [knobs](https://github.com/elishacloud/dxwrapper/wiki/Configuration#d3d9).

**Comment by niresh1234** [comment]
1. I try almost all options from d3d9-wrapper.... but `without ForceWindowedMode = 1` game stuck

2. dxwrapper only load other dll instead of system dll if dxwrapper renamed to that dll file
eg. dxwrapper renamed to d3d9.dll then load dxvk dll from some location.... and these options still not give ability to load dxwrapper(d3d9.dll) and d3d9-wrapper (d3d9.dll) at same time

3. also game still stucks when using dxwrapper WndowedMode Options

4. currently i use these hex methods which is [mentioned hare](https://github.com/doitsujin/dxvk/issues/2772#issuecomment-1201015841) **(Only for testing)**
eg. dxvk dll renamed to d9vk.dll and paste to SysWOW64 & hex edited d3d9-wrapper dll in game directory

**Comment by niresh1234** [comment]
1. I try almost all options from d3d9-wrapper.... but `without ForceWindowedMode = 1` game stuck

2. dxwrapper only load other dll instead of system dll if dxwrapper renamed to that dll file
eg. dxwrapper renamed to d3d9.dll then load dxvk dll from some location.... and these options still not give ability to load dxwrapper(d3d9.dll) and d3d9-wrapper (d3d9.dll) at same time

3. also game still stucks when using dxwrapper WndowedMode Options (when using DXVK)

4. currently i use these hex methods which is [mentioned hare](https://github.com/doitsujin/dxvk/issues/2772#issuecomment-1201015841) **(Only for testing)**
eg. dxvk dll renamed to d9vk.dll and paste to SysWOW64 & hex edited d3d9-wrapper dll in game directory

**Comment by mirh** [comment]
You don't have to use d3d9-wrapper with dxwrapper (even though I guess you could try it for starters, to make sure you got the syntax of the `RealDllPath` value right). 
And if `EnableWindowMode=1` doesn't do the trick.. then indeed it must not be just a matter of windowed mode alone (maybe check `FullscreenWindowMode`, `WindowModeBorder` and `DisableMaxWindowedMode` for starters).

**Comment by niresh1234** [comment]
Yes! Try and working with dxwrapper windowed mode... but not stable
like no-sound and **also newGame stuck** (even without DXVK)

But I think its Confirm! issue is fixed by WindowedModes related tweaks...

**Comment by Sagatt** [comment]
> Yes! Try and working with dxwrapper windowed mode... but not stable like no-sound and **also newGame stuck** (even without DXVK)
> 
> But I think its Confirm! issue is fixed by WindowedModes related tweaks...

Have you tried using GangstaPatch?

**Comment by niresh1234** [comment]
@Sagatt yes tried... But it's trusted?

Gangstapatch look like stealing entire code of silentPatch, fusionFix, d3d9Wrapper and some other mods (which is already open-source) and compile into one.... no mention credit and not mentioned what actually change? It really trusted?

**Comment by Sagatt** [comment]
> @Sagatt yes tried... But it's trusted?
> 
> Gangstapatch look like stealing entire code of silentPatch, fusionFix, d3d9Wrapper and some other mods (which is already open-source) and compile into one.... no mention credit and not mentioned what actually change? It really trusted?

I never had any problems using it, BUT i also wish their code was open source, it used to be so frankly I think it's stupid to keep it closed, for that reason I get where you're coming from.

**Comment by mirh** [comment]
> But I think its Confirm! issue is fixed by WindowedModes related tweaks...

Which one specifically?

**Comment by niresh1234** [comment]
> > But I think its Confirm! issue is fixed by WindowedModes related tweaks...
> 
> Which one specifically?

`ForceWindowedMode = 1` no matter which mode use like window or borderless

### one more thing about DxWrapper
```
[General]
RealDllPath                = C:\DXVK\d3d9.dll

[Compatibility]
EnableD3d9Wrapper          = 1
```
This two work individually (no matter if use at same time or **one ON and other OFF**)
```
EnableWindowMode           = 1      // like windowedmode
FullscreenWindowMode       = 1      // like borderkess windowedmode
```

### I mean something is working **OTHER THEN EXCLUSIVE FULLSCREEN MODE**

**Comment by niresh1234** [comment]
> > But I think its Confirm! issue is fixed by WindowedModes related tweaks...
> 
> Which one specifically?

`ForceWindowedMode = 1` no matter which mode use like window or borderless

### now one thing about DxWrapper
```
[General]
RealDllPath                = C:\DXVK\d3d9.dll

[Compatibility]
EnableD3d9Wrapper          = 1
```
This two work individually (no matter if use at same time or **one ON and other OFF**)
```
EnableWindowMode           = 1      // like windowedmode
FullscreenWindowMode       = 1      // like borderkess windowedmode
```

### I mean something is working **OTHER THEN EXCLUSIVE FULLSCREEN MODE**

**Comment by niresh1234** [comment]
> > But I think its Confirm! issue is fixed by WindowedModes related tweaks...
> 
> Which one specifically?

`ForceWindowedMode = 1` no matter which mode use like window or borderless

### now one thing about DxWrapper
```
[General]
RealDllPath                = C:\DXVK\d3d9.dll

[Compatibility]
EnableD3d9Wrapper          = 1
```
This two work individually (no matter if use at same time or **one ON and other OFF**)
```
EnableWindowMode           = 1      // like windowedmode
FullscreenWindowMode       = 1      // like borderkess windowedmode
```

### something is working **OTHER THEN EXCLUSIVE FULLSCREEN MODE**

### I Mean DXVK only Crash(notWorking) with Game Exclusive/Default Fullscreen Mode

**Comment by mirh** [comment]
I thought you had said the game still got suck when using dxwrapper WindowedMode options, but I guess you meant in the menu then? Anyhow, `FullscreenWindowMode` should be it then. 

And even that has a bunch of things it does.. It changes the window style, it forces the window position and it peeks the window to avoid the desktop thinking it's unresponsive. 
Either there's some odd ass magic with the former, or the game is doing something weird with the window size..

Can you try to play with the windows compatibility settings (from the game executable properties), or with the *InitialWindowPosition* dxwrapper options?

**Comment by niresh1234** [comment]
using `InitialWindowPosition` still same as before

**and only newGame crash, not save game and its dxwrapper issue (without DXVK still new game crash after cutscene)**
![Screenshot (265)](https://github.com/user-attachments/assets/84639b0d-3849-4954-a8cd-cdb13c9f318e)

**Comment by Sagatt** [comment]
So doesn't work and no support?

**Comment by Mrblubb** [comment]
DXVK works with Scarface, even the latest version. I used Gangsta patch & set in the settings.ini borderless fullscreen. The game runs, but, the pop-in and object loading is way slow even slower than vanilla dx9. Performance was good though, but sometimes the game crashes when it cannot load the objects. Running in native dx9 has no such issues and pop-in is like ps2.

**Comment by Aztec2012** [comment]
Any news?

**Comment by Blisto91** [comment]
Not besides that the graphical issues have been fixed.

**Comment by niresh1234** [comment]
this game still cant able to run with DXVK without using windowed or borderlessWindowed.....

### with DXVK + ExclusiveFullscreen, game still not able to run

**Comment by niresh1234** [comment]
this game still can't able to run with DXVK without using windowed or borderlessWindowed (using wrappers).....

### with DXVK + ExclusiveFullscreen, game still not able to run

**Comment by Zul479** [comment]
How do i run the game on Windowed mode?
Is there any tutorial

**Comment by Mrblubb** [comment]
@niresh1234 @Zul479 like I said before, DXVK works with this game only on windowed borderless mode otherwise it will just crash or freeze at startup. What you need is latest Gangsta patch and asi loader & its not compatible with fusion fix so remove it before using. Now after copying it to game directory, go to settings.ini, specify your resolution height and width at the top and under windowed section select Mode=2 and save. Now paste dxvk dx9 in it and run. The game should work but the pop-ins are worse than vanilla dx9 and there are crashes too (don't know if its fixed now). So, for me this game is an exception to just play with vanilla dx9 & fullscreen.

**Comment by Aztec2012** [comment]
> [@niresh1234](https://github.com/niresh1234) [@Zul479](https://github.com/Zul479) like I said before, DXVK works with this game only on windowed borderless mode otherwise it will just crash or freeze at startup. What you need is latest Gangsta patch and asi loader & its not compatible with fusion fix so remove it before using. Now after copying it to game directory, go to settings.ini, specify your resolution height and width at the top and under windowed section select Mode=2 and save. Now paste dxvk dx9 in it and run. The game should work but the pop-ins are worse than vanilla dx9 and there are crashes too (don't know if its fixed now). So, for me this game is an exception to just play with vanilla dx9 & fullscreen.

Not work for me at all.

**Comment by niresh1234** [comment]
> [@niresh1234](https://github.com/niresh1234) [@Zul479](https://github.com/Zul479) like I said before, DXVK works with this game only on windowed borderless mode otherwise it will just crash or freeze at startup. What you need is latest Gangsta patch and asi loader & its not compatible with fusion fix so remove it before using. Now after copying it to game directory, go to settings.ini, specify your resolution height and width at the top and under windowed section select Mode=2 and save. Now paste dxvk dx9 in it and run. The game should work but the pop-ins are worse than vanilla dx9 and there are crashes too (don't know if its fixed now). So, for me this game is an exception to just play with vanilla dx9 & fullscreen.

@Mrblubb before commenting anything..... check-out this entire thread..... Everything about Fullscreen and Non-Fullscreen already discussed.....

**Comment by niresh1234** [comment]
@Aztec2012 @Zul479 @Sagatt try this

Extract content inside zip file to game folder
and use d3d9.dll from dxvk x32

[extract_to_game_folder.zip](https://github.com/user-attachments/files/22664318/extract_to_game_folder.zip)

**Comment by Mrblubb** [comment]
> [@Mrblubb](https://github.com/Mrblubb) before commenting anything..... check-out this entire thread..... Everything about Fullscreen and Non-Fullscreen already discussed.....

Maybe if you weren't eager to reply to get attention but actually read and applied what I said, you'd be playing the game yourself kid. Anyways here's quick footage that the game works with dxvk
[https://youtu.be/ps43hddgXU0](url)

**Comment by niresh1234** [comment]
> Maybe if you weren't eager to reply to get attention but actually read and applied what I said, you'd be playing the game yourself kid. Anyways here's quick footage that the game works with dxvk [https://youtu.be/ps43hddgXU0](url)

@Mrblubb next time commenting anything.....  you should check-out this entire thread

I can play game with DXVK with FusionFix (I mean without applying what you said)

###### Note: screen recording looks blurry because GitHub 10mb limit

https://github.com/user-attachments/assets/5762b080-bd5e-4608-8587-872e2d8ccf66

**Comment by niresh1234** [comment]
@Sagatt @Aztec2012 @Zul479 Here the package which can run Scarface with DXVK (v2.7.1 already included)

extract to game directory and play..... or play with `_run_game.cmd` to show dxvk hud.... [scarface_play_with_DXVK.zip](https://github.com/user-attachments/files/22674640/scarface_play_with_DXVK.zip)

**Comment by Aztec2012** [comment]
> [@Sagatt](https://github.com/Sagatt) [@Aztec2012](https://github.com/Aztec2012) [@Zul479](https://github.com/Zul479) Here the package which can run Scarface with DXVK (v2.7.1 already included)
> 
> extract to game directory and play..... or play with `_run_game.cmd` to show dxvk hud.... [scarface_play_with_DXVK.zip](https://github.com/user-attachments/files/22674640/scarface_play_with_DXVK.zip)

Not works with Reshade. So only way by now is using Dgvoodoo2.
