### ISSUE TITLE
System hang and AMD driver crash when playing Turtle WoW with DXVK

### ISSUE THREAD

**Issue by DanielHoogland** [doitsujin/dxvk#5413]
Summary:
After a couple of minutes of playing Turtle WoW with DXVK, my entire system hangs, both screens turn black, and the AMD driver reports a crash. The game also crashes, but both screens recover shortly after. This issue seemed to start after updating DXVK to 2.7.1. Downgrading to 2.6.2 does not resolve it. I did not change any DXVK configuration manually, as it is handled by the Turtle WoW launcher. A logfile from the game run is attached.

Software information

Game: Turtle WoW
Settings / Mods / Addons: No additional mods or addons used; clean install

System information

GPU: AMD Radeon RX 9070 XT
Driver: 25.12.1 (latest)
OS / Wine version: Windows 11
DXVK version: 2.7.1 (also tested 2.6.2, same issue)
CPU: Ryzen 7 7800X3D

Apitrace file(s)
Not yet available

Log files: 
Attached: 

[WoW_d3d9.log](https://github.com/user-attachments/files/24384447/WoW_d3d9.log)

**Comment by K0bin** [comment]
Might be a duplicate of #5408

Any chance you could do an apitrace? [Here's a guide](https://github.com/doitsujin/dxvk/wiki/Using-Apitrace#on-windows) Unfortunately the log doesn't really tell us anything.

**Comment by DanielHoogland** [comment]
I followed the instructions for creating an apitrace, but I’m not sure how useful it will be since the crash is not tied to any specific action. The game sometimes crashes after 1 minute, sometimes after 5, etc. I ran the trace during about 6 minutes of general gameplay.

You can find the trace here: https://drive.google.com/file/d/1UyHn5d2fVrlh2j5TZpvwhoQw_5p5B7K6/view?usp=sharing

**Comment by 01dog** [comment]
+1 to this. after updating on 12/31 i get the same issues but my entire system hangs and crashes and isnt able to recover.

GPU: AMD Radeon RX 7800 XT
Driver: 25.12.1 (also crashed on an older version, don't remember which specifically tho)
OS / Wine version: Windows 11 10.0, build 26100
DXVK version: 2.7.1
CPU: Ryzen 7 7800X3D

[WoW_d3d9.log](https://github.com/user-attachments/files/24403296/WoW_d3d9.log)

**Comment by dong2g** [comment]
For what its worth, I was having the same issue and found that replacing the dxvk2.7.1 d3d9.dll with the 64-bit version works. I havent yet seen this again. 9070XT.

**Comment by mbriar** [comment]
> For what its worth, I was having the same issue and found that replacing the dxvk2.7.1 d3d9.dll with the 64-bit version works. I havent yet seen this again. 9070XT.

the only thing that does is disable dxvk and switch back to native d3d9 on windows because a 32bit game can't load the 64bit dll.

**Comment by DanielHoogland** [comment]
> > For what its worth, I was having the same issue and found that replacing the dxvk2.7.1 d3d9.dll with the 64-bit version works. I havent yet seen this again. 9070XT.
> 
> the only thing that does is disable dxvk and switch back to native d3d9 on windows because a 32bit game can't load the 64bit dll.

That explains why it would not crash hah. Without dxvk the game runs without issues indeed. The weird part is, this started after an update to the latest dxvk version but reverting to an older version does not solve this issue. Could it be a config issue? 

I tried to change dxvk.allowFse = False in the config as posted in [another](https://github.com/doitsujin/dxvk/issues/5399), but not quite similar thread but that doesn't help either.

**Comment by mbriar** [comment]
> The weird part is, this started after an update to the latest dxvk version but reverting to an older version does not solve this issue. Could it be a config issue?

Did you also update your driver during this time? With how unstable the amd windows vulkan driver seems to be recently with dxvk, i would not be surprised if it was a driver issue. Sadly now that AMD dropped support for amdvlk, it is impossible to test recent versions of the windows vulkan driver on linux.

**Comment by DanielHoogland** [comment]
> > The weird part is, this started after an update to the latest dxvk version but reverting to an older version does not solve this issue. Could it be a config issue?
> 
> Did you also update your driver during this time? With how unstable the amd windows vulkan driver seems to be recently with dxvk, i would not be surprised if it was a driver issue. Sadly now that AMD dropped support for amdvlk, it is impossible to test recent versions of the windows vulkan driver on linux.

I just checked but no, my graphics driver was updated the 11th of December and this happened much later.

**Comment by DanielHoogland** [comment]
> > The weird part is, this started after an update to the latest dxvk version but reverting to an older version does not solve this issue. Could it be a config issue?
> 
> Did you also update your driver during this time? With how unstable the amd windows vulkan driver seems to be recently with dxvk, i would not be surprised if it was a driver issue. Sadly now that AMD dropped support for amdvlk, it is impossible to test recent versions of the windows vulkan driver on linux.

I was too quick to dismiss your suggestion. Even though the driver was installed on December 11th and I noticed the issue much later, I must not have played much because reverting back to a previous AMD driver did in fact solve the issue. 

**For the record, the crashing went completely away when I reverted the AMD GPU driver from version 25.12.1 back to 25.11.1** 

I'm not sure if this issue needs to be closed now but if it does let me know. 

Ping @01dog and @dong2g

**Comment by mbriar** [comment]
Just anecdotally:  [RPCS3 recently disabled VK_EXT_attachment_feedback_loop_layout](https://github.com/RPCS3/rpcs3/pull/17765) on AMD windows to work around GPU hangs/driver crashes. DXVK d3d9 might be the only other thing even using this extension, so it could be related.

**Comment by GoingXX** [comment]
+1 to this. After I rolled back to version 2.5.1\2.5.2\2.5.3, the problem was resolved.
GPU: 6600
CPU: 9900X

**Comment by Polarite** [comment]
issue persists to this day on 2.7.2.
Using 2.5.2 "fixes" the issue.

**Comment by K0bin** [comment]
Report it to AMD, it's not a DXVK bug.
